version: 0.2
phases:
  pre_build:
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket=$BUCKET --output-template-file output.yaml
artifacts:
  files:
    - 'output.yaml'
